### ISSUE TITLE
Cancelacion 2022

### ISSUE THREAD

**Issue by eislasq** [phpcfdi/xml-cancelacion#26]
Hola. Hace falta actualizar para cumplir el requerimiento del SAT para 2022. 

http://omawww.sat.gob.mx/tramitesyservicios/Paginas/documentos/Documentacion_tecnica.pdf pagina 65 

Aquí se puede ver el cambio necesario. Básicamente se agregan 2 parámetros: Motivo y FolioSustitucion.
 
![cancelacion](https://user-images.githubusercontent.com/7228352/148630300-2ef685f1-6cb4-4417-9765-3b8f032d6df3.png)
 
Tengo ya el código de manera local para esta actualización. pero me faltan las pruebas. ¿Alguien ya está trabajando en esto?

**Comment by eclipxe13** [comment]
Es justo en lo que estoy trabajando, en un momento espero liberar la versión actualizada (habrá cambio de versión mayor)
